Final/Final/Controllers/EmpleadoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final.Models;

namespace Final.Controllers
{
    public class EmpleadoesController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        public ActionResult ActiveClients(string option, string search)
        {
            //return View(db.Empleados.Where(x => x.Nombre.Contains(searching) || searching == null).ToList());
            //return View(db.Empleados.Where(x => x.Nombre.Contains(search)|| search == null ).ToList());
            var empleados = db.Empleados.Where(e => e.Estatus == true);
            if (option == "Nombre")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(db.Empleados.Where(x => x.Nombre.Contains(search) && x.Estatus == true || search == null && x.Estatus == true).ToList());
            }
           // else if (option == "Departamento")
           // {
                //var query = db.Empleados.Join(db.Departamentos, emp => emp.Departamento,
                //dep => dep.Id,(emp,dep)=>new {db }    )
                //return View(db.Departamentos.Select(c => c.Empleados) && db.Empleados.Where(c.Departamentos == search || search == null).ToList());
                //return View(db.Empleados.Where(x => x.Departamentos.Contains(search) && x.Estatus == true || search == null && x.Estatus == true).ToList())
           // }
            else
            {
                return View(empleados.ToList());
            }
            //else
            //{
            //    //return View(db.Students.Where(x = > x.Name.StartsWith(search) || search == null).ToList());
            //}
        }

        //public ActionResult InMonth(DateTime month)
        //{
        //    var empleados = db.Empleados.Where(e => e.Fecha_Ingreso == );


        //    return View(empleados.ToList());
        //}

        public ActionResult InactiveClient()
        {
            var empleados = db.Empleados.Where(e => e.Estatus == false);


            return View(empleados.ToList());
        }

        // GET: Empleadoes
        public ActionResult Index()
        {
            var empleados = db.Empleados.Include(e => e.Cargo1).Include(e => e.Departamento1);
            return View(empleados.ToList());
        }

        // GET: Empleadoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // GET: Empleadoes/Create
        public ActionResult Create()
        {
            ViewBag.Cargo = new SelectList(db.Cargoes, "Id", "Nombre_Cargo");
            ViewBag.Departamento = new SelectList(db.Departamentos, "Id", "Nombre_Departamento");
            return View();
        }

        // POST: Empleadoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Apellido,Telefono,Departamento,Cargo,Fecha_Ingreso,Salario,Estatus")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Empleados.Add(empleado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Cargo = new SelectList(db.Cargoes, "Id", "Nombre_Cargo", empleado.Cargo);
            ViewBag.Departamento = new SelectList(db.Departamentos, "Id", "Nombre_Departamento", empleado.Departamento);
            return View(empleado);
        }

        // GET: Empleadoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cargo = new SelectList(db.Cargoes, "Id", "Nombre_Cargo", empleado.Cargo);
            ViewBag.Departamento = new SelectList(db.Departamentos, "Id", "Nombre_Departamento", empleado.Departamento);
            return View(empleado);
        }

        // POST: Empleadoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Apellido,Telefono,Departamento,Cargo,Fecha_Ingreso,Salario,Estatus")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Cargo = new SelectList(db.Cargoes, "Id", "Nombre_Cargo", empleado.Cargo);
            ViewBag.Departamento = new SelectList(db.Departamentos, "Id", "Nombre_Departamento", empleado.Departamento);
            return View(empleado);
        }

        // GET: Empleadoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: Empleadoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleado empleado = db.Empleados.Find(id);
            db.Empleados.Remove(empleado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
   
}

Final/Final/Views/Empleadoes/ActiveClients.cshtml
@model IEnumerable<Final.Models.Empleado>
@{
    ViewBag.Title = "ActiveClients";
}

<h2>Empleados Activos</h2>
@using (Html.BeginForm("ActiveClients", "Empleadoes", FormMethod.Get))
{

    <b> Search Option: </b>

    @Html.RadioButton("option", "Nombre") <text> Nombre </text>

    @Html.RadioButton("option", "Departamento")<text>Departamento</text> @Html.TextBox("search")

    @*@Html.TextBox("Searching")<input type="submit" value="Search"/>*@

    <input type="submit" name="submit" value="Buscar" />
}

<br />
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            Fecha Ingreso
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estatus)
        </th>
        <th>
            Cargo
        </th>
        <th>
            Departamento
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.TextBoxFor(ModelItem => item.Fecha_Ingreso, "{0:dd-MMM-yyyy}", new { @style = "outline: none; border: none; ", @readonly = true })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @if (@item.Estatus)
                {<text>Activo</text>}
            else
            {<text>Inactivo</text>}
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo1.Nombre_Cargo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento1.Nombre_Departamento)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript">
        $(function () {

            $('.datepicker').datepicker({ dateFormat: "mm-dd-yy" });
        })
    </script>
}

Final/Final/Views/Empleadoes/Create.cshtml
@model Final.Models.Empleado

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Agregar Empleado</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departamento, "Departamento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Departamento", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Departamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo, "Cargo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cargo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Ingreso, "Fecha Ingreso", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Ingreso, new { htmlAttributes = new { @class = "form-control datepicker", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Fecha_Ingreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Estatus, htmlAttributes: new { @checked = true, @style = "display: none" })
                    @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Ir a Lista de Empleados", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript">
        $(function () {

            $('.datepicker').datepicker({ dateFormat: "mm-dd-yy" });
        })
    </script>
}

Final/Final/Views/Empleadoes/Delete.cshtml
@model Final.Models.Empleado

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Ingreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Ingreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargo1.Nombre_Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargo1.Nombre_Cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamento1.Nombre_Departamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamento1.Nombre_Departamento)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Final/Final/Views/Empleadoes/Details.cshtml
@model Final.Models.Empleado

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Ingreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Ingreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargo1.Nombre_Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargo1.Nombre_Cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamento1.Nombre_Departamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamento1.Nombre_Departamento)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Final/Final/Views/Empleadoes/Edit.cshtml
@model Final.Models.Empleado

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departamento, "Departamento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Departamento", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Departamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo, "Cargo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cargo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Ingreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Ingreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Ingreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estatus)
                    @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Final/Final/Views/Empleadoes/InMonth.cshtml
@{
    ViewBag.Title = "InMonth";
}

<h2>InMonth</h2>

Final/Final/Views/Empleadoes/InactiveClient.cshtml
@model IEnumerable<Final.Models.Empleado>
@{
    ViewBag.Title = "InactiveClient";
}

<h2>Empleados Inactivos</h2>

<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            Fecha Ingreso
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estatus)
        </th>
        <th>
            Cargo
        </th>
        <th>
            Departamento
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.TextBoxFor(ModelItem => item.Fecha_Ingreso, "{0:dd-MMM-yyyy}", new { @style = "outline: none; border: none; ", @readonly = true })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @if (@item.Estatus)
                {<text>Activo</text>}
            else
            {<text>Inactivo</text>}
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo1.Nombre_Cargo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento1.Nombre_Departamento)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript">
        $(function () {

            $('.datepicker').datepicker({ dateFormat: "mm-dd-yy" });
        })
    </script>
}

Final/Final/Views/Empleadoes/Index.cshtml
@model IEnumerable<Final.Models.Empleado>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Empleados</h2>

<p>
    @Html.ActionLink("Agregar", "Create")
</p>
@using (Html.BeginForm("Index", "Home", FormMethod.Get))
{

    <b> Search Option: </b> @Html.RadioButton("option", "Name") <text>Name</text>

    @Html.RadioButton("option", "Gender") <text> Gender </text>

    @Html.RadioButton("option", "Subjects")<text>Subject</text> @Html.TextBox("search")

    <input type="submit" name="submit" value="Buscar" />
}
<br />
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            Fecha Ingreso
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estatus)
        </th>
        <th>
            Cargo
        </th>
        <th>
            Departamento
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.TextBoxFor(ModelItem => item.Fecha_Ingreso, "{0:dd-MMM-yyyy}", new { @style = "outline: none; border: none; ", @readonly = true })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @if (@item.Estatus)
                {<text>Activo</text>}
            else
            {<text>Inactivo</text>}
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo1.Nombre_Cargo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento1.Nombre_Departamento)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript">
        $(function () {

            $('.datepicker').datepicker({ dateFormat: "mm-dd-yy" });
        })
    </script>
}